# Generated by Django 6.0.1 on 2026-02-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='casual', max_length=100),
            preserve_default=False,
        ),
    ]
