# Generated by Django 6.0.1 on 2026-02-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
    ]
