# Generated by Django 6.0.1 on 2026-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('subtext', models.TextField()),
                ('image', models.ImageField(upload_to='hero/')),
                ('primary_cta_text', models.CharField(max_length=50)),
                ('primary_cta_link', models.CharField(max_length=200)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
